### ISSUE TITLE
The number of bread slices is not specified

### ISSUE THREAD

**Issue by MidLifeXis** [lclrobotics/github_demo#2]
The number of slices of bread is not specified.  How many should be used?

**Comment by MidLifeXis** [comment]
@lclrobotics/formalemus_11353 and @lclrobotics/t-birds_11351, see if you can figure out how to find the current instructions (hint: look at the ```<> Code``` link at the top)

![image](https://user-images.githubusercontent.com/54983/31924034-28e8fb12-b844-11e7-996f-00ad52db1486.png)

Also see if you can add additional error / problem reports or enhancement requests (hint: look for the ```Issues``` link)

![image](https://user-images.githubusercontent.com/54983/31924072-621e9900-b844-11e7-9320-26341136c186.png)

**Comment by MidLifeXis** [comment]
Oh, @lclrobotics/coaches can also participate.

**Comment by seffertz** [comment]
Leave a comment

**Comment by meeshcas** [comment]
This issue is reopened

**Comment by YellowGuy** [comment]
I say 2 because it would make a whole sammich

**Comment by CH-Prog** [comment]
PotatOS

**Comment by MidLifeXis** [comment]
Are we done here?

**Comment by MidLifeXis** [comment]
:shipit:
